version: "3.3"

services:
  webapp:
    image: "mdpetters/hygroscopicitytestbed:new"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 3
    ports:
      - "1234:1234"
