version: "3.3"

services:
  hygroscopicitytestbed:
    image: "mdpetters/hygroscopicitytestbed:new"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 2
    ports:
      - "1234:1234"

  virtualdma:
    image: "mdpetters/virtualdma:latest"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 2
    ports:
      - "1235:1234"

